name: swarming-course
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyterlab
  - ipykernel
  - ipython
  - ipywidgets
  - ipympl
  - numpy
  - pandas
  - scipy
  - matplotlib=3.10.*
  - opencv
